version: "3.7"
services:
  backend:
    build: 
      context: ./backend
    depends_on:
      - db
      - redis
    links:
      - db:database
      - redis:redisdb
    ports:
      - "3333:3333"
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend

    ports:
      - "3000:3000"
  db:
    image: mongo
  redis:
    image: redis:alpine