version: "3.7"
services:
  backend:
    build: 
      context: ./backend
    depends_on:
      - db
      - redis
    networks:
      api:
        aliases:
          - api
          - backend
      databases:
        aliases:
          - backend
    ports:
      - "3333:3333"
  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    networks:
      api:
        aliases:
          - frontend
    ports:
      - "3000:3000"
  db:
    image: mongo
    networks:
      databases:
        aliases:
          - database
  redis:
    image: redis:alpine
    networks:
      databases:
        aliases:
          - redis
networks:
  databases:
  api: